"""
claude_reranker.py
──────────────────
Reranks FAISS candidates using Claude. Claude returns only (id, explanation);
all other metadata is hydrated from the candidate lookup — never generated by Claude.
"""

import os
import json
import anthropic
from dotenv import load_dotenv

load_dotenv()

client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))
MODEL  = "claude-sonnet-4-20250514"

# ── PROMPTS ───────────────────────────────────────────────────────────────────

SYSTEM_PROMPT = """You are Reelio's recommendation engine — a film-literate assistant
that selects and explains movie recommendations.

You will receive:
1. A numbered list of candidate movies
2. The user's stated preferences

Your task:
- Pick the 5 best matches given the user's preferences
- For each, write a SHORT (2-3 sentence) explanation referencing tone, themes, or style

Output ONLY a valid JSON array. No markdown, no code fences, no preamble.
Each element must have exactly two keys: "id" (integer) and "explanation" (string).

Example:
[
  {"id": 27205, "explanation": "A cerebral thriller with layered reality. Shares the same mind-bending structure as your picks."},
  {"id": 157336, "explanation": "Epic and emotionally grounded sci-fi. Matches the ambitious scope of your selections."}
]"""


def _build_prompt(candidates: list[dict], resolved_seeds: list[str], preferences: dict) -> str:
    lines = []
    for i, c in enumerate(candidates, 1):
        runtime = f"{c['runtime']}min" if c.get("runtime") else "?"
        genre   = c.get("genre_string") or "Unknown genre"
        rating  = c.get("vote_average") or "?"
        year    = c.get("release_year") or "?"
        lines.append(f"{i:>2}. [id={c['id']}] {c['title']} ({year}) | {genre} | {runtime} | {rating}/10")

    prefs = []
    if resolved_seeds:
        prefs.append(f"Seed movies: {', '.join(resolved_seeds)}")
    if preferences.get("genre"):
        prefs.append(f"Genre: {preferences['genre']}")
    if preferences.get("mood"):
        prefs.append(f"Vibe: {preferences['mood']}")
    if preferences.get("runtime_max"):
        prefs.append(f"Max runtime: {preferences['runtime_max']} min")
    if preferences.get("group"):
        prefs.append(f"Watching with: {preferences['group']}")

    prefs_block = "\n".join(prefs) or "No specific preferences."
    cands_block = "\n".join(lines)

    return f"USER PREFERENCES\n{prefs_block}\n\nCANDIDATES\n{cands_block}\n\nReturn the 5 best as JSON."


# ── PUBLIC API ────────────────────────────────────────────────────────────────

def rerank(candidates: list[dict], resolved_seeds: list[str], preferences: dict) -> list[dict]:
    """
    Ask Claude to pick and explain top 5 from candidates.
    Hydrates all metadata from candidate dicts — Claude only provides id + explanation.
    Falls back to top-5 FAISS order if Claude call or parse fails.
    """
    if not candidates:
        return []

    # Build id→candidate lookup from immutable copies to prevent mutation
    candidate_by_id = {c["id"]: dict(c) for c in candidates}

    try:
        response = client.messages.create(
            model=MODEL,
            max_tokens=1200,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": _build_prompt(candidates, resolved_seeds, preferences)}],
        )

        raw = response.content[0].text.strip()

        # Strip any accidental markdown fences
        if "```" in raw:
            parts = raw.split("```")
            # Take the content between the first pair of fences
            raw = parts[1] if len(parts) > 1 else parts[0]
            if raw.lower().startswith("json"):
                raw = raw[4:]
            raw = raw.strip()

        picks = json.loads(raw)

        if not isinstance(picks, list):
            raise ValueError(f"Claude returned non-list: {type(picks)}")

        results = []
        for pick in picks[:5]:
            pid = pick.get("id")
            exp = pick.get("explanation", "")
            if pid is None:
                print(f"  [reranker] pick missing id, skipping: {pick}")
                continue
            source = candidate_by_id.get(int(pid))
            if source is None:
                print(f"  [reranker] id {pid} not in candidates, skipping")
                continue
            results.append({**source, "explanation": exp})

        if not results:
            raise ValueError("Claude returned 0 usable picks — falling back")

        print(f"  [reranker] Claude picked {len(results)} movies")
        return results

    except Exception as e:
        print(f"  [reranker] ERROR: {e} — falling back to FAISS top 5")
        return _fallback(candidates)


def rerank_mock(candidates: list[dict], **_) -> list[dict]:
    """Dev mock — returns top 5 with placeholder explanations. Does NOT mutate input."""
    results = []
    for c in candidates[:5]:
        m = dict(c)   # copy — never mutate the shared _movie_index entry
        m["explanation"] = (
            f"'{m['title']}' shares strong thematic similarities with your picks. "
            f"[{m.get('genre_string', 'Unknown genre')}]"
        )
        results.append(m)
    return results


def _fallback(candidates: list[dict]) -> list[dict]:
    """Return top 5 candidates with a generic explanation. Does NOT mutate input."""
    results = []
    for c in candidates[:5]:
        m = dict(c)
        m.setdefault("explanation", "Recommended based on semantic similarity to your selections.")
        results.append(m)
    return results
